name: Conduit
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ocaml-compiler: ["4.13", "4.14", "5.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
